spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ${GATEWAY_OAUTH2_CLIENT_ID}
            clientSecret: ${GATEWAY_OAUTH2_CLIENT_SECRET}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
